# Generated by Django 5.1 on 2024-09-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
